eureka:
  instance:
    securePort: 443
    securePortEnabled: true
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
    
fortune:
  fallbackFortune: Your future is... curious!
